apiVersion: apps/v1
kind: Deployment

metadata: 
  name: day1
  namespace: kul
  labels: 
    client: optum
    type: training
  annotations: 
    prodsupport: support@thinknyx.com
    supportnumber: "9876543210"
    githubrepo: "https://github.com/kmayer10/thinknyx-optum.git"
    
spec: 
  replicas: 4
  template: 
    metadata: 
      name: kul
      labels:
        client: optum
        day: "1"
    spec: 
      containers: 
      - name: kul
        image: httpd
        resources: 
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits: 
            memory: "96Mi"
            cpu: "200m"
      nodeSelector: 
        bu: cde
  selector: 
    matchLabels: 
      client: optum
      day: "1"
