apiVersion: v1
kind: Pod
metadata: 
  name: kul
  namespace: kul
  labels:
    client: optum
    day: "1"
spec: 
  volumes: 
  - name: secret-volume
    secret:
      secretName: secret-keys
  containers: 
  - name: kul
    image: httpd
    envFrom: 
    - configMapRef: 
        name: cm-1
    - secretRef: 
        name: db-cred
    imagePullSecrets: 
    - name: docker-cred
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/tmp/keys/"
