apiVersion: v1
kind: Service
metadata: 
  name: day1-svc
  namespace: kul
spec: 
  ports: 
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30000
  
  type: NodePort

  selector: 
    day: "1"
