apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
  namespace: kul
spec: 
  ports: 
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30002

  - name: https
    protocol: TCP
    port: 443
    nodePort: 30003

  externalIPs:
  - 3.238.102.254
  - 3.235.94.16
  
  type: NodePort

  selector: 
    app: nginx
