apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: aggregator
aggregationRule: 
  clusterRoleSelectors: 
  - matchLabels:
      aggregate: "true"
rules: 
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
      
