apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: read-nodes

subjects: 
- kind: User
  name: kul
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: vk
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: deepak
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: optum-cluster-role
  apiGroup: rbac.authorization.k8s.io
