apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: optum-cluster-role

rules: 
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","watch","list"]
#- apiGroups: ["apps"]
#  resources: ["deployments","replicasets"]
#  verbs: ["get","watch","list"]

