apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: optum-read-pods
  namespace: kul
subjects: 
- kind: User
  name: kul
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: optumrole
  apiGroup: rbac.authorization.k8s.io
