apiVersion: v1
kind: Service
metadata: 
  name: day1-svc
  namespace: kul
spec: 
  ports: 
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30000

  - name: https
    protocol: TCP
    port: 443
    nodePort: 30001

  externalIPs:
  - 3.238.102.254
  - 3.235.94.16
  
  type: NodePort

  selector: 
    client: {{ .Values.selectors.appName }}
